unset POSTGRES_SERVER
unset POSTGRES_USER
unset POSTGRES_PASSWORD
unset POSTGRES_DB
unset SQLALCHEMY_DATABASE_URI
unset base_url
unset SECRET_KEY
unset ALGORITHM
unset REDIS
unset DATA_URL
unset WEBHOOK_HOST
unset API_URL

unset WEBAPP_HOST
unset WEBAPP_PORT

unset API_ID
unset API_HASH
unset APP_TITLE
unset SHORT_NAME
unset TG_BOT_TOKEN

set POSTGRES_SERVER=
set POSTGRES_USER=
set POSTGRES_PASSWORD=
set POSTGRES_DB=
set SQLALCHEMY_DATABASE_URI=
set base_url=
set SECRET_KEY=
set ALGORITHM=
set REDIS=
set DATA_URL=
set WEBHOOK_HOST=
set API_URL